const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const Schema = mongoose.Schema;

const patientSchema = new Schema({
    demography: {
        hospitalId: { type: String },
        branchId: { type: String },
        surgeonId: { type: String },
        uhid: { type: String },
        studyid: { type: String },
        firstname: { type: String },
        middlename: { type: String },
        lastname: { type: String },
        dob: { type: String },
        age: { type: String },
        gender: { type: String },
        height: { type: String },
        weight: { type: String },
        bmi: { type: String },
        address: { type: String },
        city: { type: String },
        state: { type: String },
        country: { type: String },
        zipcode: { type: String },
        telephoneno: { type: Number },
        phoneno: { type: Number },
        email: { type: String },
        side: { type: String },
        bilateraltype: { type: String },
        combination: { type: String },
        type: { type: String }
    },
    preoperative: {
        surgerydate: { type: String },
        surgeonname: { type: String },
        etiology: { type: String },
        etiologyothername: { type: String },
        valgus: { type: String },
        varus: { type: String },
        flexion: { type: String },
        joint: [{
            otherJoint: { type: String },
            selected: { type: Boolean, default: false }
        }],
        symptoms: [{
            symptomsName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        onsetsymptom: { type: String },
        noyear: { type: String },
        symptomaggravated: [{
            aggravatedName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        Comorbidities: [{
            comorbiditiesName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        Previouskneesurgeries: [{
            PreviouskneesurgeriesName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        steroid: { type: String },
        viscosupplement: { type: String },
        flexiondeformity: { type: String },
        hyperextension: { type: String },
        retropatellar: { type: String },
        patellartracking: { type: String },
        quadricepspower: { type: String },
        diagnosis: { type: String },
        diagnosisothername: { type: String },
        causerevision: [{
            causerevisionName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        prostheticType: { type: String },
        precompany: { type: String },
        predesign: { type: String },
        indexsurgery: { type: String },
        revisionsurgeries: { type: String },
        previouskneesurgery: { type: String },
        painrest: { type: String },
        previousscar: { type: String },
        sinustract: { type: String },
        previousflaps: { type: String },
        hiporif: [{
            hiporifName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        deformity: [{
            deformityName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        apparent: [{
            apparentName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        limp1: { type: String },
        limptrue: [{
            limptrueName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        limp2: { type: String },
        vitaminD: { type: String },
        vitaminB12: { type: String }
    },


    radiology: {
        implantsitu: [{
            implantsituName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        rad_valgus: { type: String },
        rad_varus: { type: String },
        rad_patella: { type: String },
        rad_stressfracture: [{
            stressfractureName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        rad_vcaangle: { type: String },
        rad_availabilityct: { type: String },
        rad_availabilitymri: { type: String },
        rad_vitaminD: { type: String },
        rad_vitaminB12: { type: String },
        rad_femoralcomponent: { type: String },
        rad_tibialcomponent: { type: String },
        rad_femoralrotation: { type: String },
        rad_tibialrotation: { type: String },
        rad_availablemrict: { type: String },
        rad_esr: { type: String },
        rad_crp: { type: String },
        rad_ficat: { type: String },
        rad_grading: [{
            gradingName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        rad_protrusio: [{
            protrusioName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        rad_DDH: [{
            dDHName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        rad_grade: { type: String },
        rat_croweclassification: { type: String },
        rat_paproskyclassification: { type: String },
        rat_femurclassification: { type: String },
        rat_morphotype: { type: String },
        rad_LLD: { type: String },
        rad_osteopenia: { type: String }
    },
    intraoperative: {
        intra_surgicalplan: { type: String },
        intra_procedure: { type: String },
        intra_navigation: { type: String },
        intra_drapes: { type: String },
        intra_hoods: { type: String },
        intra_prophylactic: { type: String },
        intra_tranexamicoption: { type: String },
        intra_anaesthesia: [{
            anaesthesiaName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_grade: { type: String },
        intra_position: { type: String },
        intra_approach: { type: String },
        intra_softtissue: [{
            softtissueName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_STSO: { type: String },
        intra_boneGraft: { type: String },
        intra_impaction: [{
            impactionName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_bulk: [{
            bulkName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_tourniquet: { type: String },
        intra_tourniquetpressure: { type: String },
        intra_arthrotomy: { type: String },
        intra_femoralcomp: { type: String },
        intra_patellarstatus: { type: String },
        intra_aoriclassification: { type: String },
        intra_femoralDefect: { type: String },
        intra_tibialsizing: { type: String },
        intra_spacer: { type: String },
        intra_patellarretinaculum: { type: String },
        intra_medialcollateral: { type: String },
        intra_lateralcollateral: { type: String },
        intra_pattendon: { type: String },
        intra_tibialdefect: { type: String },
        intra_aoriclassification: { type: String },
        intra_patellaouterbridgeclassification: { type: String },
        intra_patellarthickness: { type: String },
        intra_acl: { type: String },
        intra_pcl: { type: String },
        intra_mcl: { type: String },
        intra_lcl: { type: String },
        intra_varus: [{
            varusName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_valgus: [{
            valgusName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_flexion: [{
            flexionName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_distalfemoral: { type: String },
        intra_resurfacing: { type: String },
        intra_reconstruction: [{
            reconstructionName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_defectReconstruction: { type: String },
        intra_femoralstem: { type: String },
        intra_stem: { type: String },
        intra_tibialstem: { type: String },
        intra_tstem: { type: String },
        intra_cement: { type: String },
        intra_antibiotic: { type: String },
        intra_viscosity: { type: String },
        intra_uncement: { type: String },
        intra_acetabular: { type: String },
        intra_screws: { type: String },
        intra_bearing: { type: String },
        intra_acetabularliner: { type: String },
        intra_femoralcement: { type: String },
        intra_femoralantibiotic: { type: String },
        intra_femoralviscosity: { type: String },
        intra_femoraluncement: { type: String },
        intra_femoralbearing: { type: String },
        intra_cocktail: { type: String },
        intra_complications: { type: String },
        intra_complicationdetail: { type: String },
        intra_company: { type: String },
        intra_femoralcompany: { type: String },
        intra_model: { type: String },
        intra_femoralmodel: { type: String },
        intra_design: { type: String },
        intra_Size: { type: String },
        intra_femoralSize: { type: String },
        intra_femoralSize: { type: String },
        intra_tibialSize: { type: String },
        intra_patellarSize: { type: String },
        intra_insertPoly: { type: String },
        intra_componentStability: [{
            componentStabilityName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_contracture: { type: String },
        intra_hyperextension: { type: String },
        intra_medialLaxity: { type: String },
        intra_patellarTracking: { type: String },
        intra_posteriorclosure: { type: String },
        intra_operativehour: { type: String },
        intra_operativeminute: { type: String },
        intra_bloodloss: { type: String },
        intra_drains: { type: String },
        intra_mechanical: [{
            mechanicalName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_pharmacological: [{
            pharmacologicalName: { type: String },
            selected: { type: Boolean, default: false }
        }],
        intra_information: { type: String },
        intra_LLD: { type: String },
        intra_prophylaxis: { type: String }
    },
    postoperative: [{
        post_date: { type: String },
        post_side: { type: String },
        post_posteriorslope: { type: String },
        post_notes: { type: String },
        post_hipkneeankle: { type: String },
        post_filename: { type: String },
        post_filetype: { type: String }
    }],
    preoperativescores: {
       
        prekneescore: {
            kneescore_walking: { type: String },
            kneescore_stairs: { type: String },
            kneescore_point: { type: String },
            kneescore_lateral: { type: String },
            kneescore_posterior: { type: String },
            kneescore_extension: { type: String },
            kneescore_flexion: { type: String },
            kneescore_malalignment: { type: String },
            kneescore_rest: { type: String },
            totalkneescore: { type: String },
            kneescore_functionwalk: { type: String },
            kneescore_functionstairs: { type: String },
            kneescore_functiondeductions: { type: String },
            totalfunctionscore: { type: String }
        },
        prewomacscore: {
            womac_walking: { type: String },
            womac_Stair: { type: String },
            womac_nocturnal: { type: String },
            womac_rest: { type: String },
            womac_weight: { type: String },
            womac_stiffness: { type: String },
            womac_stiffnessoccurring: { type: String },
            womac_descendingstairs: { type: String },
            womac_ascendingstairs: { type: String },
            womac_rising: { type: String },
            womac_standing: { type: String },
            womac_bending: { type: String },
            womac_surface: { type: String },
            womac_gettingcar: { type: String },
            womac_shopping: { type: String },
            womac_puttingsocks: { type: String },
            womac_lying: { type: String },
            womac_takingsocks: { type: String },
            womac_risingbed: { type: String },
            womac_gettingbath: { type: String },
            womac_sitting: { type: String },
            womac_gettingon: { type: String },
            womac_domestic: { type: String },
            womac_lightdomestic: { type: String },
            totaldivide: { type: String },
            totalwomacscore: { type: String }
        },
        presf36score: {
            sf36_generalhealth: { type: String },
            generalhealth: { type: String },
            sf36_ratehealth: { type: String },
            ratehealth: { type: String },
            sf36_vigorous: { type: String },
            vigorous: { type: String },
            sf36_moderate: { type: String },
            moderate: { type: String },
            sf36_lifting: { type: String },
            lifting: { type: String },
            sf36_severalflights: { type: String },
            severalflights: { type: String },
            sf36_oneflights: { type: String },
            oneflights: { type: String },
            sf36_bending: { type: String },
            bending: { type: String },
            sf36_walking: { type: String },
            walking: { type: String },
            sf36_severalblocks: { type: String },
            severalblocks: { type: String },
            sf36_oneblock: { type: String },
            oneblock: { type: String },
            sf36_dressing: { type: String },
            dressing: { type: String },
            sf36_spentactivities: { type: String },
            spentactivities: { type: String },
            sf36_accomplished: { type: String },
            accomplished: { type: String },
            sf36_workactivities: { type: String },
            workactivities: { type: String },
            sf36_performing: { type: String },
            performing: { type: String },
            sf36_spentwork: { type: String },
            spentwork: { type: String },
            sf36_accomplishedless: { type: String },
            accomplishedless: { type: String },
            sf36_carefully: { type: String },
            carefully: { type: String },
            sf36_socialactivities: { type: String },
            socialactivities: { type: String },
            sf36_bodilypain: { type: String },
            bodilypain: { type: String },
            sf36_paininterfere: { type: String },
            paininterfere: { type: String },
            sf36_feelfull: { type: String },
            feelfull: { type: String },
            sf36_nervous: { type: String },
            nervous: { type: String },
            sf36_dumps: { type: String },
            dumps: { type: String },
            sf36_calm: { type: String },
            calm: { type: String },
            sf36_energy: { type: String },
            energy: { type: String },
            sf36_downhearted: { type: String },
            downhearted: { type: String },
            sf36_feelworn: { type: String },
            feelworn: { type: String },
            sf36_happyperson: { type: String },
            happyperson: { type: String },
            sf36_feeltired: { type: String },
            feeltired: { type: String },
            sf36_physicalhealth: { type: String },
            physicalhealth: { type: String },
            sf36_sick: { type: String },
            sick: { type: String },
            sf36_healthy: { type: String },
            healthy: { type: String },
            sf36_getworse: { type: String },
            getworse: { type: String },
            sf36_excellent: { type: String },
            excellent: { type: String },
            sf36_physicalscore: { type: String },
            sf36_rolelimitation: { type: String },
            sf36_emotional: { type: String },
            sf36_energyfatigue: { type: String },
            sf36_wellbeing: { type: String },
            sf36_Socialfunction: { type: String },
            sf36_pain: { type: String },
            sf36_health: { type: String }
        },
        prekujalascore: {
            kujalascore_limp: { type: String },
            kujalascore_support: { type: String },
            kujalascore_walking: { type: String },
            kujalascore_stairs: { type: String },
            kujalascore_running: { type: String },
            kujalascore_squatting: { type: String },
            kujalascore_jumping: { type: String },
            kujalascore_prolonged: { type: String },
            kujalascore_pain: { type: String },
            kujalascore_swelling: { type: String },
            kujalascore_painful: { type: String },
            kujalascore_atrophy: { type: String },
            kujalascore_flexion: { type: String },
            totalkujalascore: { type: String }
        },
        preoxfordscore: {
            oxfordscore_pain: { type: String },
            oxfordscore_trouble: { type: String },
            oxfordscore_sick: { type: String },
            oxfordscore_walk: { type: String },
            oxfordscore_painful: { type: String },
            oxfordscore_limping: { type: String },
            oxfordscore_kneel: { type: String },
            oxfordscore_troubled: { type: String },
            oxfordscore_interfered: { type: String },
            oxfordscore_felt: { type: String },
            oxfordscore_household: { type: String },
            oxfordscore_stairs: { type: String },
            totaloxfordscore: { type: String },
        },
         harrishipscore: {
            harriship_pain: { type: String },
            harriship_walked: { type: String },
            harriship_socks: { type: String },
            harriship_transportation: { type: String },
            harriship_support: { type: String },
            harriship_limp: { type: String },
            harriship_stairs: { type: String },
            harriship_sitting: { type: String },
            harriship_30degrees: { type: String },
            harriship_10degrees: { type: String },
            harriship_10degreesextension: { type: String },
            harriship_discrepancy: { type: String },
            harriship_flexion: { type: String },
            harriship_abduction: { type: String },
            harriship_extRotation: { type: String },
            harriship_adduction: { type: String },
            totalharrishipscore: { type: String }
        },
         statificationscore: {
            statification_joint6month: { type: String },
            statification_joint12month: { type: String },
            statification_regular6month: { type: String },
            statification_regular12month: { type: String },
            statification_sport6month: { type: String },
            statification_sport12month: { type: String },
            statification_meet6month: { type: String },
            statification_meet12month: { type: String },
            statification_scale6month: { type: String },
            statification_scale12month: { type: String },
            statification_operation6month: { type: String },
            statification_operation12month: { type: String },
            statification_recommend6month: { type: String },
            statification_recommend12month: { type: String },
            totalstatificationscore: { type: String }
        }
    },
    postoperativedetail: {
        month: { type: String },
        year: { type: String },
    },
    postoperativescores: {

        kneescore: {
            kneescore_walking: { type: String },
            kneescore_stairs: { type: String },
            kneescore_point: { type: String },
            kneescore_lateral: { type: String },
            kneescore_posterior: { type: String },
            kneescore_extension: { type: String },
            kneescore_flexion: { type: String },
            kneescore_malalignment: { type: String },
            kneescore_rest: { type: String },
            totalkneescore: { type: String },
            kneescore_functionwalk: { type: String },
            kneescore_functionstairs: { type: String },
            kneescore_functiondeductions: { type: String },
            totalfunctionscore: { type: String }
        },
        womacscore: {
            womac_walking: { type: String },
            womac_Stair: { type: String },
            womac_nocturnal: { type: String },
            womac_rest: { type: String },
            womac_weight: { type: String },
            womac_stiffness: { type: String },
            womac_stiffnessoccurring: { type: String },
            womac_descendingstairs: { type: String },
            womac_ascendingstairs: { type: String },
            womac_rising: { type: String },
            womac_standing: { type: String },
            womac_bending: { type: String },
            womac_surface: { type: String },
            womac_gettingcar: { type: String },
            womac_shopping: { type: String },
            womac_puttingsocks: { type: String },
            womac_lying: { type: String },
            womac_takingsocks: { type: String },
            womac_risingbed: { type: String },
            womac_gettingbath: { type: String },
            womac_sitting: { type: String },
            womac_gettingon: { type: String },
            womac_domestic: { type: String },
            womac_lightdomestic: { type: String },
            totaldivide: { type: String },
            totalwomacscore: { type: String }
        },
        sf36score: {
            sf36_generalhealth: { type: String },
            generalhealth: { type: String },
            sf36_ratehealth: { type: String },
            ratehealth: { type: String },
            sf36_vigorous: { type: String },
            vigorous: { type: String },
            sf36_moderate: { type: String },
            moderate: { type: String },
            sf36_lifting: { type: String },
            lifting: { type: String },
            sf36_severalflights: { type: String },
            severalflights: { type: String },
            sf36_oneflights: { type: String },
            oneflights: { type: String },
            sf36_bending: { type: String },
            bending: { type: String },
            sf36_walking: { type: String },
            walking: { type: String },
            sf36_severalblocks: { type: String },
            severalblocks: { type: String },
            sf36_oneblock: { type: String },
            oneblock: { type: String },
            sf36_dressing: { type: String },
            dressing: { type: String },
            sf36_spentactivities: { type: String },
            spentactivities: { type: String },
            sf36_accomplished: { type: String },
            accomplished: { type: String },
            sf36_workactivities: { type: String },
            workactivities: { type: String },
            sf36_performing: { type: String },
            performing: { type: String },
            sf36_spentwork: { type: String },
            spentwork: { type: String },
            sf36_accomplishedless: { type: String },
            accomplishedless: { type: String },
            sf36_carefully: { type: String },
            carefully: { type: String },
            sf36_socialactivities: { type: String },
            socialactivities: { type: String },
            sf36_bodilypain: { type: String },
            bodilypain: { type: String },
            sf36_paininterfere: { type: String },
            paininterfere: { type: String },
            sf36_feelfull: { type: String },
            feelfull: { type: String },
            sf36_nervous: { type: String },
            nervous: { type: String },
            sf36_dumps: { type: String },
            dumps: { type: String },
            sf36_calm: { type: String },
            calm: { type: String },
            sf36_energy: { type: String },
            energy: { type: String },
            sf36_downhearted: { type: String },
            downhearted: { type: String },
            sf36_feelworn: { type: String },
            feelworn: { type: String },
            sf36_happyperson: { type: String },
            happyperson: { type: String },
            sf36_feeltired: { type: String },
            feeltired: { type: String },
            sf36_physicalhealth: { type: String },
            physicalhealth: { type: String },
            sf36_sick: { type: String },
            sick: { type: String },
            sf36_healthy: { type: String },
            healthy: { type: String },
            sf36_getworse: { type: String },
            getworse: { type: String },
            sf36_excellent: { type: String },
            excellent: { type: String },
            sf36_physicalscore: { type: String },
            sf36_rolelimitation: { type: String },
            sf36_emotional: { type: String },
            sf36_energyfatigue: { type: String },
            sf36_wellbeing: { type: String },
            sf36_Socialfunction: { type: String },
            sf36_pain: { type: String },
            sf36_health: { type: String }
        },
        kujalascore: {
            kujalascore_limp: { type: String },
            kujalascore_support: { type: String },
            kujalascore_walking: { type: String },
            kujalascore_stairs: { type: String },
            kujalascore_running: { type: String },
            kujalascore_squatting: { type: String },
            kujalascore_jumping: { type: String },
            kujalascore_prolonged: { type: String },
            kujalascore_pain: { type: String },
            kujalascore_swelling: { type: String },
            kujalascore_painful: { type: String },
            kujalascore_atrophy: { type: String },
            kujalascore_flexion: { type: String },
            totalkujalascore: { type: String }
        },
        oxfordscore: {
            oxfordscore_pain: { type: String },
            oxfordscore_trouble: { type: String },
            oxfordscore_sick: { type: String },
            oxfordscore_walk: { type: String },
            oxfordscore_painful: { type: String },
            oxfordscore_limping: { type: String },
            oxfordscore_kneel: { type: String },
            oxfordscore_troubled: { type: String },
            oxfordscore_interfered: { type: String },
            oxfordscore_felt: { type: String },
            oxfordscore_household: { type: String },
            oxfordscore_stairs: { type: String },
            totaloxfordscore: { type: String }
        },
        statificationscore: {
            statification_joint6month: { type: String },
            statification_joint12month: { type: String },
            statification_regular6month: { type: String },
            statification_regular12month: { type: String },
            statification_sport6month: { type: String },
            statification_sport12month: { type: String },
            statification_meet6month: { type: String },
            statification_meet12month: { type: String },
            statification_scale6month: { type: String },
            statification_scale12month: { type: String },
            statification_operation6month: { type: String },
            statification_operation12month: { type: String },
            statification_recommend6month: { type: String },
            statification_recommend12month: { type: String },
            totalstatificationscore: { type: String }
        },
         harrishipscore: {
            harriship_pain: { type: String },
            harriship_walked: { type: String },
            harriship_socks: { type: String },
            harriship_transportation: { type: String },
            harriship_support: { type: String },
            harriship_limp: { type: String },
            harriship_stairs: { type: String },
            harriship_sitting: { type: String },
            harriship_30degrees: { type: String },
            harriship_10degrees: { type: String },
            harriship_10degreesextension: { type: String },
            harriship_discrepancy: { type: String },
            harriship_flexion: { type: String },
            harriship_abduction: { type: String },
            harriship_extRotation: { type: String },
            harriship_adduction: { type: String },
            totalharrishipscore: { type: String }
        },

    },

    imageupload: [{
        imagename: { type: String },
        imagetype: { type: String },
        imagesize: { type: String },
        image: { type: String },
        type: { type: String }
    }]

}, { collection: 'patient' });

module.exports = mongoose.model('patient', patientSchema);